### ISSUE TITLE
Change viewGroups to display groups in lexicographic order

### ISSUE THREAD

**Issue by zzzlou** [AY2425S1-CS2103T-T16-3/tp#219]
I think it would be nice to display group names based on lexicographic order?

For example in the following image, the order of the group names could be changed to group2, group3, group4

<img width="731" alt="Screenshot 2024-10-30 at 10 33 02 PM" src="https://github.com/user-attachments/assets/241b43e7-f1e1-43b9-9537-6d63af2310dc">

**Comment by seah-minlong** [comment]
Hmm I would think having them in insertion order would be better? Since in actual use, I don't think people will really name the groups as group2, group3. Having an lexicographic ordering then wrt the group names like NUS, NTU wouldn't make much sense too.

**Comment by voldiemort** [comment]
A new Group view UI has since been created, but still the Groups can only be viewed in original inserted order.

One possible fix, if we decide it needs to be fixed, is a sort command for Groups similar to that for persons. Though given the feature freeze soon, I don't think we'll have time to implement that. Given that, I'm going ahead to close this issue.
